/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.scala-application-conventions")
    scala
}

dependencies {
    implementation("org.scala-lang:scala-library:2.13.14")
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

tasks.withType(ScalaCompile::class.java) {
    scalaCompileOptions.additionalParameters = listOf(
        "-Ytasty-reader",
        "-Ytasty-no-annotations"
    )
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
