/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.example.utilities.StringUtils

import org.apache.commons.text.WordUtils

object App {

  trait Example {}

  def main(args: Array[String]): Unit = {

    val example: Example forSome { type T } = new Example {
      type T = String
    }

    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
  }
}
